# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('located_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mi_number', models.CharField(max_length=11, unique=True)),
                ('fb_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('postal_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('year_of_study', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], max_length=7)),
                ('present_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City')),
                ('present_college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
