# Generated by Django 2.0.7 on 2018-08-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionsEvent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mi_number', models.CharField(max_length=11, unique=True)),
                ('fb_id', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cr_referral_code', models.CharField(max_length=7, null=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('postal_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('dob', models.CharField(default='0', max_length=10)),
                ('year_of_study', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], max_length=7)),
                ('checkedin', models.IntegerField(default=0)),
                ('present_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City')),
                ('present_college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.WorkshopsEvent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='present_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City'),
        ),
        migrations.AddField(
            model_name='group',
            name='present_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College'),
        ),
        migrations.AddField(
            model_name='college',
            name='assignedcl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='college',
            name='located_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City'),
        ),
    ]
