# Generated by Django 2.0.7 on 2018-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fb_id',
            new_name='google_id',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='myteam', max_length=11),
            preserve_default=False,
        ),
    ]
