# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20170807_1923'),
        ('users', '0002_auto_20170807_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionsEvent')),
                ('members', models.ManyToManyField(blank=True, to='users.UserProfile')),
            ],
        ),
    ]
