# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mobile_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='present_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City'),
        ),
        migrations.AddField(
            model_name='group',
            name='present_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College'),
        ),
    ]
