# Generated by Django 2.0.7 on 2018-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180905_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='multicity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
