# Generated by Django 2.0.7 on 2018-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180907_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
    ]
