# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170810_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
