# Generated by Django 2.0.7 on 2018-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
