# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170811_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id']},
        ),
    ]
