# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170908_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='assignedcl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
