# Generated by Django 2.0.7 on 2018-10-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActualCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('assignedcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ActualCity')),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='assignedcl',
        ),
        migrations.AddField(
            model_name='city',
            name='actual_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ActualCity'),
        ),
        migrations.AddField(
            model_name='college',
            name='actual_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ActualCollege'),
        ),
    ]
