# Generated by Django 2.0.7 on 2018-12-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181005_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopparticipant',
            name='participant',
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='name',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proshows.ProshowsEvent'),
        ),
    ]
