# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20170810_0809'),
        ('users', '0010_college_assignedcl'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.WorkshopsEvent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
