# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_workshopparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', unique=True),
        ),
    ]
