# Generated by Django 2.0.7 on 2019-08-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181219_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.MuticityCompetitionsEvent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(blank=True, default='NULL', max_length=200, null=True),
        ),
    ]
