# Generated by Django 2.0.7 on 2019-09-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190819_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.MuticityCompetitionsEvent'),
        ),
    ]
