# Generated by Django 2.0.7 on 2019-09-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_muticitycompetitionsevent'),
        ('users', '0013_auto_20190910_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='eventMI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.CompetitionsEvent'),
        ),
    ]
