# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171207_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checkedin',
            field=models.IntegerField(default=0),
        ),
    ]
