# Generated by Django 2.0.7 on 2019-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_group_eventmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
    ]
