# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_checkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cr_referral_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
