# Generated by Django 2.0.7 on 2018-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivewireBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('bandmembers', models.TextField()),
                ('hometown', models.CharField(max_length=100)),
                ('preferred_city', models.CharField(choices=[('pune', 'pune'), ('bangalore', 'bangalore'), ('delhi', 'delhi'), ('shillong', 'shillong'), ('mumbai', 'mumbai')], max_length=10)),
                ('original_composition', models.CharField(max_length=200)),
            ],
        ),
    ]
