# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivewireBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('bandmembers', models.TextField()),
                ('hometown', models.CharField(max_length=100)),
                ('preferred_city', models.CharField(choices=[('Pune', 'Pune'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Shillong', 'Shillong'), ('Mumbai', 'Mumbai')], max_length=10)),
                ('original_composition', models.CharField(max_length=200)),
            ],
        ),
    ]
