# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewireband',
            name='emailid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='livewireband',
            name='preferred_city',
            field=models.CharField(choices=[('pune', 'pune'), ('bangalore', 'bangalore'), ('delhi', 'delhi'), ('shillong', 'shillong'), ('mumbai', 'mumbai')], max_length=10),
        ),
    ]
