# Generated by Django 2.0.7 on 2019-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0002_auto_20190924_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewireband',
            name='facebook_link',
            field=models.TextField(),
        ),
    ]
