# Generated by Django 2.0.7 on 2019-09-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0003_auto_20190924_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livewireband',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='livewireband',
            name='manager',
        ),
    ]
