# Generated by Django 2.0.7 on 2019-09-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0004_auto_20190924_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewireband',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
