# Generated by Django 2.0.7 on 2019-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0006_auto_20190925_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewireband',
            name='original_composition',
            field=models.TextField(blank=True),
        ),
    ]
