# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20170810_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsevent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workshops.WorkshopsGenre'),
        ),
    ]
