# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('venue', models.CharField(choices=[('Convocation Hall', 'Convocation Hall'), ('Lecture Hall Complex (LCH)', 'Lecture Hall Complex (LCH)'), ('LT PCSA', 'LT PCSA'), ('Gymkhana Grounds', 'Gymkhana Grounds'), ('NCC Grounds', 'NCC Grounds'), ('FC Kohli Auditorium (FCK)', 'FC Kohli Auditorium (FCK)'), ('New Swimming Pool', 'New Swimming Pool'), ('Kendriya Vidyalaya (KV)', 'Kendriya Vidyalaya (KV)'), ('Student Activity Center (SAC)', 'Student Activity Center (SAC)'), ('SJM SOM', 'SJM SOM'), ('Open Air Theatre (OAT)', 'Open Air Theatre (OAT)'), ('MB Lawns', 'MB Lawns'), ('Physics Parking Lot', 'Physics Parking Lot'), ('H10 T-Point', 'H10 T-Point'), ('PCSA Backlawns', 'PCSA Backlawns'), ('SAC Parking Lot', 'SAC Parking Lot'), ('SAC Backyard', 'SAC Backyard'), ('Old Swimming Pool', 'Old Swimming Pool')], max_length=50)),
                ('description', models.TextField()),
                ('starttime', models.CharField(max_length=4)),
                ('endtime', models.CharField(max_length=4)),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('genre', models.CharField(choices=[('Competitions', 'Competitions'), ('Proshows', 'Proshows'), ('Workshops', 'Workshops'), ('Concerts', 'Concerts'), ('Informals', 'Informals')], max_length=20)),
            ],
        ),
    ]
