# Generated by Django 2.0.7 on 2018-08-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('contingent_strength', models.IntegerField(default=0)),
                ('selected_contingent_strength', models.IntegerField(default=0)),
                ('is_equal', models.IntegerField(default=0)),
                ('strength_alloted', models.IntegerField(default=-1)),
                ('is_approved', models.IntegerField(default=0)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContingentLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por', models.CharField(max_length=100)),
                ('wascllastyear', models.CharField(max_length=3)),
                ('iscrcurrently', models.CharField(max_length=3)),
                ('timesmiattended', models.IntegerField()),
                ('nocpiclink', models.TextField()),
                ('clprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContingentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.IntegerField(default=0)),
                ('is_imp', models.IntegerField(default=0)),
                ('has_paid', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='contingent',
            name='contingent_members',
            field=models.ManyToManyField(blank=True, to='cl.ContingentMember'),
        ),
    ]
