# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingentleader',
            name='hasporcurrently',
        ),
        migrations.AddField(
            model_name='contingentleader',
            name='por',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
