# Generated by Django 2.0.7 on 2018-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingentleader',
            name='college',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
