# Generated by Django 2.0.7 on 2018-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0002_contingentleader_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingentleader',
            name='timesmiattended',
            field=models.CharField(max_length=1),
        ),
    ]
