# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170908_2030'),
        ('cl', '0003_remove_contingentleader_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=50)),
                ('cl_mobile_number', models.CharField(max_length=10, unique=True)),
                ('contingent_strength', models.IntegerField()),
                ('strength_alloted', models.IntegerField()),
                ('status', models.IntegerField()),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl.ContingentLeader')),
                ('contigent_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City')),
                ('contingent_college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College')),
                ('contingent_members', models.ManyToManyField(blank=True, to='users.UserProfile')),
            ],
        ),
    ]
