# Generated by Django 2.0.7 on 2018-10-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0003_auto_20181009_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingentleader',
            name='city',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='contingentleader',
            name='year_of_study',
            field=models.CharField(default='NULL', max_length=6),
        ),
    ]
