# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0004_contingent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contingentleader',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='contingent',
            name='cl_mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
