# Generated by Django 2.0.7 on 2018-10-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0004_auto_20181011_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
