# Generated by Django 2.0.7 on 2018-10-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0005_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cl.College'),
        ),
    ]
