# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_college_assignedcl'),
        ('cl', '0006_auto_20171107_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=50)),
                ('cl_mobile_number', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('contingent_strength', models.IntegerField(default=0)),
                ('is_equal', models.IntegerField(default=0)),
                ('strength_alloted', models.IntegerField(default=-1)),
                ('is_approved', models.IntegerField(default=0)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('contigent_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City')),
                ('contingent_college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.College')),
            ],
        ),
        migrations.CreateModel(
            name='ContingentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.IntegerField(default=0)),
                ('is_imp', models.IntegerField(default=0)),
                ('has_paid', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='contingent',
            name='contingent_members',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cl.ContingentMember'),
        ),
    ]
