# Generated by Django 2.0.7 on 2018-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0007_contingentmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingentmember',
            name='cl_approve',
            field=models.IntegerField(default=0),
        ),
    ]
