# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0007_auto_20171109_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingent',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contingent',
            name='contingent_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cl.ContingentMember'),
        ),
    ]
