# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0008_auto_20171109_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent',
            name='cl_mobile_number',
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='cl_name',
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='contigent_city',
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='contingent_college',
        ),
    ]
