# Generated by Django 2.0.7 on 2018-10-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0008_contingentmember_cl_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='fem_alloted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='male_alloted',
            field=models.IntegerField(default=0),
        ),
    ]
