# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0009_auto_20171109_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contingent',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='contingent_members',
        ),
        migrations.AddField(
            model_name='contingent',
            name='contingent_members',
            field=models.ManyToManyField(blank=True, null=True, to='cl.ContingentMember'),
        ),
    ]
