# Generated by Django 2.0.7 on 2018-10-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0009_auto_20181026_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='f_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='m_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='selected_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='selected_m',
            field=models.IntegerField(default=0),
        ),
    ]
