# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0010_auto_20171109_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='selected_contingent_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contingent',
            name='contingent_members',
            field=models.ManyToManyField(blank=True, to='cl.ContingentMember'),
        ),
    ]
