# Generated by Django 2.0.7 on 2018-10-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0010_auto_20181026_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingentmember',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cl.College'),
        ),
    ]
