# Generated by Django 2.0.7 on 2018-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsevent',
            name='LYP_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionsevent',
            name='LYP_logo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
