# Generated by Django 2.0.7 on 2018-08-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20180812_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsevent',
            name='LYP_partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='competitionsevent',
            name='LYP_description',
            field=models.TextField(blank=True),
        ),
    ]
