# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20170807_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsevent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competitions.CompetitionsGenre'),
        ),
    ]
