# Generated by Django 2.0.7 on 2018-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20180827_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsevent',
            name='status',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
