# Generated by Django 2.0.7 on 2018-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competitionsevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsevent',
            name='status',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
