# Generated by Django 2.0.7 on 2018-10-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20181005_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsevent',
            name='LYP_img',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
