# Generated by Django 2.0.7 on 2019-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competitionsevent_lyp_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuticityCompetitionsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
