# Generated by Django 2.0.7 on 2019-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_muticitycompetitionsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsevent',
            name='queries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitionsevent',
            name='winners',
            field=models.TextField(blank=True),
        ),
    ]
