# Generated by Django 2.0.7 on 2018-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cr_referral_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
