# Generated by Django 2.0.7 on 2018-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagica', '0002_auto_20180923_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='bus_pickup',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
